[tool.poetry]
name = "fakeit-rest"
version = "0.1.0"
description = ""
authors = ["Farman Pirzada <farmann.pirz@gmail.com>"]
readme = "README.md"
packages = [{include = "fakeit_rest"}]

[tool.poetry.dependencies]
python = "^3.11"
Faker = "^30.8.0"
fastapi = "^0.115.3"
uvicorn = "^0.32.0"
pydantic = "^2.9.2"
PyYAML = "^6.0.2"
pytest = "^8.3.3"
httpx = "^0.27.2"
asyncio = "^3.4.3"
python-multipart = "^0.0.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
